
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "user" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>

development:
  <<: *default
  database: vkiri_development

production:
  primary: &primary_production
    <<: *default
    database: vkiri_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: vkiri_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: vkiri_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: vkiri_production_cable
    migrations_paths: db/cable_migrate
